use S11
go

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ -- phantom reads
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE -- phantom reads solutions
BEGIN TRAN;
SELECT * FROM Orase WHERE Oid = (SELECT MAX(Oid) FROM Orase);
WAITFOR DELAY '00:00:05';
SELECT * FROM Orase WHERE Oid = (SELECT MAX(Oid) FROM Orase);
COMMIT TRAN;