use S11
go

DELETE FROM Orase WHERE Oid = (SELECT MAX(Oid) FROM Orase);
SELECT * FROM Orase;

BEGIN TRAN;
WAITFOR DELAY '00:00:05';
INSERT INTO Orase(Nume) VALUES ('Phantom404');
COMMIT TRAN;